{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gubexplorer.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gubexplorer.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.auth.username | required "auth.username is required when auth.enabled=true and no existingSecret" | quote }}
  password: {{ .Values.auth.password | required "auth.password is required when auth.enabled=true and no existingSecret" | quote }}
{{- end }}
