{{- if and .Values.kubeconfig.enabled (not .Values.kubeconfig.existingSecret) .Values.kubeconfig.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gubexplorer.fullname" . }}-kubeconfig
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gubexplorer.labels" . | nindent 4 }}
type: Opaque
stringData:
  kubeconfig: |-
    {{- .Values.kubeconfig.value | nindent 4 }}
{{- end }}
