apiVersion: v2
name: gubexplorer
description: Web UI to explore and manage Kubernetes namespace resources
type: application
version: 1.0.3
appVersion: "1.2.0"
keywords:
  - kubernetes
  - explorer
  - dashboard
home: https://github.com/arnaudta/gubexplorer
